language: node_js
node_js:
  - '0.8'
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-project' ]; then cd .. && eval "mv $currentfolder generator-project" && cd generator-project; fi

